### ISSUE TITLE
运行lint时报错，找不到#--debug-brk

### ISSUE THREAD

**Issue by areyouse7en** [umijs/umi-lint#1]
yarn lint时报错
![image](https://user-images.githubusercontent.com/3938443/53310973-f0cccd80-38e9-11e9-8c2b-46f3b6089cea.png)

依赖和配置如下：
![image](https://user-images.githubusercontent.com/3938443/53310989-fcb88f80-38e9-11e9-8c82-7bc82ed31447.png)
![image](https://user-images.githubusercontent.com/3938443/53311010-0641f780-38ea-11e9-949a-204fc2e6a34e.png)

**Comment by clock157** [comment]
这个 bash 注释 windows 下可能存在问题，我重发了一个版本，你试下。

**Comment by areyouse7en** [comment]
lint通过了，但是提交的时候，哈士奇好像有问题
另外之前项目里已有的tslint.yml里，extends的规则得删掉。

![image](https://user-images.githubusercontent.com/3938443/53383053-3dc7a700-39b1-11e9-8cb0-cdb0e91fe6aa.png)

**Comment by clock157** [comment]
看起来是 bin 程序在 windows 下的兼容性问题，谢谢反馈，我稍后跟进下。

**Comment by clock157** [comment]
@areyouse7en 请问你用的是哪一个 npm 客户端？

**Comment by clock157** [comment]
已修复，试一下。 @areyouse7en

**Comment by areyouse7en** [comment]
node 8.11.4, npm 5.6.0, yarn 1.13.0, win10
解决了，谢谢~

**Comment by clock157** [comment]
问题原因是 lint-staged 使用了 npm-which，全路径的 bin 在 windows 下存在兼容性问题，并且也不需要使用全路径的 bin。但是可能潜在问题，待观察。
