### ISSUE TITLE
与vscode插件eslint的问题

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi-lint#2]
vscode下 eslint插件配置eslint.options的configFile为node_modules/umi-lint/.eslintrc
会提示在路径下找不到 eslint-config-prettier

**Comment by clock157** [comment]
你项目下需要有.eslintrc

**Comment by xiexingen** [comment]
> 你项目下需要有.eslintrc

觉着既然precommit的时候检测用的是umi-lint里面的配置，那么有没办法在 对应的在vscode中的eslint插件中也应该使用umi-lint里面的.eslintrc文件 而不需要再重新在项目中增加一个.eslintrc、重新安装lint相关的package 
如果项目中另外再添加.eslintrc文件 是不是会存在vscode插件提示的错误跟precommit时候提示的不一致的问题

**Comment by clock157** [comment]
umi-lint 没有提供配置，它里面的配置是给umi-lint 这个项目做代码质量检查用的，precommit 也不会用到 umi-lint 里的配置。你的项目，你需要有 eslintrc, eslint 会自动使用该配置。你可以测试一下

**Comment by xiexingen** [comment]
> umi-lint 没有提供配置，它里面的配置是给umi-lint 这个项目做代码质量检查用的，precommit 也不会用到 umi-lint 里的配置。你的项目，你需要有 eslintrc, eslint 会自动使用该配置。你可以测试一下

明白了 明白了 ，谢谢谢谢
