### ISSUE TITLE
stylelint 在提交时报错

### ISSUE THREAD

**Issue by areyouse7en** [umijs/umi-lint#3]
git提交的时候回报stylelint的错，Error: No configuration provided

![image](https://user-images.githubusercontent.com/3938443/53854079-09806600-4003-11e9-89eb-d759272f4c59.png)

node 8.11.4, npm 5.6.0, yarn 1.13.0, win10, vscode

**Comment by clock157** [comment]
你要使用 stylelint，需要有配置文件 `.stylelintrc`

**Comment by clock157** [comment]
你可以借鉴 [antd-pro](https://github.com/ant-design/ant-design-pro/blob/master/.stylelintrc.json) 的配置。

**Comment by areyouse7en** [comment]
ok, 3Q
